#!/bin/bash
  
tmux -f $VMSCRIPTS/tmux.conf new-session -d -s kernel_debugging 'sleep 1 && cd $KERNEL && gdb vmlinux -ex "target remote :1234" -ex "c"; bash'
tmux -f $VMSCRIPTS/tmux.conf split-window -h 'sleep 10 && ssh_vm; cd && bash'
tmux -f $VMSCRIPTS/tmux.conf split-window -v 'cd && boot_vm --debug; tmux kill-session -t kernel_debugging'
tmux -f $VMSCRIPTS/tmux.conf attach -t kernel_debugging